language: node_js
node_js: stable
branches:
  only:
  - master
addons:
  ssh_know_hosts:
  - 47.102.143.46
before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
 ssh-add /tmp/deploy_rsa
install:
- yarn
before_script:
script: yarn run build
after_success:
- rsync -az --delete ./dist/* root@47.102.143.46:/root/html